name: dart_event_sourcing_generator
description: dart_event_sourcing_generator
version: '1.0.0'
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: ^0.11.4
  build: ^1.2.2
  source_gen: ^0.9.0
  dart_event_sourcing:
    path: ../dart-event-sourcing
dev_dependencies:
  build_test: '^0.10.12+1'
  build_runner: '^1.7.4'
  test: '^1.12.0'
